# Ejercicio Modelo Lineal usando Moore-(algo...)

In [2]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
phi = np.array([[1,1], [1,2], [1,3], [1,4], [1,5]])
y = np.array([2, 4, 7, 10, 13]) # Es posible que no haya una ecuación.
phi, y

(array([[1, 1],
        [1, 2],
        [1, 3],
        [1, 4],
        [1, 5]]),
 array([ 2,  4,  7, 10, 13]))

In [4]:
pseudo_inv = np.linalg.inv(phi.T @ phi) @ phi.T
pseudo_inv

array([[ 0.8,  0.5,  0.2, -0.1, -0.4],
       [-0.2, -0.1,  0. ,  0.1,  0.2]])

In [5]:
params = pseudo_inv @ y
np.round(params, 2)

array([-1.2,  2.8])

In [19]:
# X = (X - X.mean()) / X.std() # Normalización de características
# Y = (Y - Y.mean()) / Y.std() # Normalización de etiquetas

X = np.array([[1], [2], [3]])


In [20]:
phi = np.array([np.ones(len(X)), X]).T
phi

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 3) + inhomogeneous part.

In [14]:
w = np.zeros((2, 1)) #Pesos iniciales
lr = 0.1 #Tasa de aprendizaje
w, lr

(array([[0.],
        [0.]]),
 0.1)

In [16]:
epochs = 100 #Número de iteraciones para el entrenamiento
for epoch in range(epochs):
    ols = 0.5 * (y - phi @ w)**2 #Error cuadrático medio
    grad = -phi.T @ (y - phi @ w) #Gradiente
    w = w + lr * grad #Actualización de pesos
w

array([[-1.96155944e+152, -3.92311888e+152, -6.86545804e+152,
        -9.80779720e+152, -1.27501364e+153],
       [-7.08185198e+152, -1.41637040e+153, -2.47864819e+153,
        -3.54092599e+153, -4.60320379e+153]])