# Ejercicio Modelo Lineal usando Moore-(algo...)

In [15]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


In [ ]:
phi = np.array([[1,1], [1,2], [1,3], [1,4], [1,5]])
y = np.array([2, 4, 7, 10, 13]) # Es posible que no haya una ecuación.
phi, y

(array([[1, 1],
        [1, 2],
        [1, 3]]),
 array([2, 5, 7]))

In [17]:
pseudo_inv = np.linalg.inv(phi.T @ phi) @ phi.T
pseudo_inv

array([[ 1.33333333,  0.33333333, -0.66666667],
       [-0.5       ,  0.        ,  0.5       ]])

In [18]:
params = pseudo_inv @ y
np.round(params, 2)

array([-0.33,  2.5 ])